# Generated by Django 2.2.8 on 2022-08-22 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeeTable',
            fields=[
                ('attendeeID', models.IntegerField(primary_key=True, serialize=False)),
                ('fName', models.CharField(max_length=120)),
                ('lName', models.CharField(max_length=120)),
                ('position', models.CharField(max_length=120)),
                ('attendance', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyLinkTable',
            fields=[
                ('companyLinkID', models.IntegerField(primary_key=True, serialize=False)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyTable',
            fields=[
                ('companyID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventTable',
            fields=[
                ('eventID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('location', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ProposeNewTimeTable',
            fields=[
                ('proposeNewTimeID', models.IntegerField(primary_key=True, serialize=False)),
                ('newStartTime', models.TimeField()),
                ('newEndTime', models.TimeField()),
                ('companyLinkID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.CompanyLinkTable')),
            ],
        ),
        migrations.CreateModel(
            name='MessageTable',
            fields=[
                ('messageID', models.IntegerField(primary_key=True, serialize=False)),
                ('messageText', models.TextField()),
                ('proposeNewTimeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.ProposeNewTimeTable')),
            ],
        ),
        migrations.CreateModel(
            name='EmailTable',
            fields=[
                ('emailID', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('attendeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.AttendeeTable')),
            ],
        ),
        migrations.CreateModel(
            name='DateTable',
            fields=[
                ('dateID', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('attendeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.AttendeeTable')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRepTable',
            fields=[
                ('companyRepID', models.IntegerField(primary_key=True, serialize=False)),
                ('fName', models.CharField(max_length=120)),
                ('lName', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.CompanyTable')),
            ],
        ),
        migrations.AddField(
            model_name='companylinktable',
            name='companyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.CompanyTable'),
        ),
        migrations.AddField(
            model_name='companylinktable',
            name='dateID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.DateTable'),
        ),
        migrations.AddField(
            model_name='companylinktable',
            name='eventID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.EventTable'),
        ),
        migrations.CreateModel(
            name='BlockTimeTable',
            fields=[
                ('blockTimeID', models.IntegerField(primary_key=True, serialize=False)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.CompanyTable')),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.EventTable')),
            ],
        ),
        migrations.CreateModel(
            name='AccompliceTable',
            fields=[
                ('accompliceID', models.IntegerField(primary_key=True, serialize=False)),
                ('fName', models.CharField(max_length=120)),
                ('lName', models.CharField(max_length=120)),
                ('position', models.CharField(max_length=120)),
                ('attendeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.AttendeeTable')),
            ],
        ),
    ]
